replicaCount: 1

image:
  repository: hello-world
  tag: local
  digest: ''
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080
  nodePort: null

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: '1'
    memory: 512Mi
